### PR TITLE
Fix NotallyActivity restore state by moving NotallyModel.isFirstInstance

### LINKED ISSUE #20: Tasks Disappear When Changing App Language
Tasks are removed when changing the app language in the settings.

showcase

https://github.com/user-attachments/assets/ca5a3cb4-795d-47e1-a986-7426a4f744be

### PR DESCRIPTION
**Pull request by PhilKes**
Fixes #20

### CODE REVIEW

File: app/src/main/java/com/omgodse/notally/activities/NotallyActivity.kt [hunk 1]
```diff
@@ -82,17 +82,13 @@ abstract class NotallyActivity(private val type: Type) : AppCompatActivity() {
         setContentView(binding.root)
 
         lifecycleScope.launch {
-            if (model.isFirstInstance) {
```
Comment (PhilKes) [inline app/src/main/java/com/omgodse/notally/activities/NotallyActivity.kt:85]: I'm not really sure why this was introduced in the first place, perhaps some minor performance improvement.
But it prevented the the Views from being properly re-created after changing the language of the app.
